Repository beyond-SW-Camp-14th-5rE5/3Seok1Team, pull requests merged in 2025-02, with the labels that each got.

#7 [GAME] / #2 / 게임 설명 출력
  hotfist/src/main/java/com/seok/hotfist/aggregate/MasterScore.java
  hotfist/src/main/java/com/seok/hotfist/repository/GameRepository.java
  hotfist/src/main/java/com/seok/hotfist/service/GameService.java
Labels: :sparkles: enhancement

#8 [GAME] / #3 / 컴퓨터, 플레이어 점수 구현
  hotfist/src/main/java/com/seok/hotfist/aggregate/MasterScore.java
  hotfist/src/main/java/com/seok/hotfist/service/GameService.java
Labels: :sparkles: enhancement

#9 [GAME] / #4, #5 / 게임 종료, 점수 판단 구현
  hotfist/src/main/java/com/seok/hotfist/service/GameService.java
Labels: :sparkles: enhancement

#20 [GAME] / #6, #19 / 회원별 점수 최근 count개만 저장
  hotfist/src/main/java/com/seok/hotfist/aggregate/GameLog.java
  hotfist/src/main/java/com/seok/hotfist/aggregate/Status.java
  hotfist/src/main/java/com/seok/hotfist/db/gameLogDB.dat
  hotfist/src/main/java/com/seok/hotfist/repository/GameRepository.java
  hotfist/src/main/java/com/seok/hotfist/service/GameService.java
Labels: :sparkles: enhancement

#23 회원 가입 기능
  hotfist/src/main/java/com/seok/hotfist/aggregate/Member3.java
  hotfist/src/main/java/com/seok/hotfist/aggregate/Status.java
  hotfist/src/main/java/com/seok/hotfist/db/memberDB.dat
  hotfist/src/main/java/com/seok/hotfist/db/rankDB.dat
  hotfist/src/main/java/com/seok/hotfist/repository/MemberRepository.java
  hotfist/src/main/java/com/seok/hotfist/run/Application3.java
  hotfist/src/main/java/com/seok/hotfist/service/MemberService.java
  hotfist/src/main/java/com/seok/hotfist/stream/MyObjectOutput.java
Labels: :sparkles: enhancement

#25 [GAME] / #22 / 게임 기록 더미 데이터 추가
  hotfist/src/main/java/com/seok/hotfist/db/gameLogDB.dat
  hotfist/src/main/java/com/seok/hotfist/repository/GameRepository.java
  hotfist/src/main/java/com/seok/hotfist/run/Application2.java
  hotfist/src/main/java/com/seok/hotfist/service/GameService.java
Labels: :test_tube: test

#38 [GAME] / #34, #21 / 게임 끝나면 데이터 저장
  hotfist/src/main/java/com/seok/hotfist/aggregate/GameLog.java
  hotfist/src/main/java/com/seok/hotfist/db/gameLogDB.dat
  hotfist/src/main/java/com/seok/hotfist/repository/GameRepository.java
  hotfist/src/main/java/com/seok/hotfist/run/Application2.java
  hotfist/src/main/java/com/seok/hotfist/service/GameService.java
Labels: :sparkles: enhancement

#42 [MEMBER] / #41 / 멤버 더미데이터 추가
  hotfist/src/main/java/com/seok/hotfist/db/gameLogDB.dat
  hotfist/src/main/java/com/seok/hotfist/db/memberDB.dat
  hotfist/src/main/java/com/seok/hotfist/repository/MemberRepository.java
Labels: :zap: Update

#45 [GAME] / #33, #14, #16 / 게임 데이터 랭킹 반영
  hotfist/src/main/java/com/seok/hotfist/repository/GameRepository.java
  hotfist/src/main/java/com/seok/hotfist/run/Application2.java
  hotfist/src/main/java/com/seok/hotfist/run/Application3.java
  hotfist/src/main/java/com/seok/hotfist/service/GameService.java
  hotfist/src/main/java/com/seok/hotfist/service/RankService.java
Labels: :sparkles: enhancement

#47 [GAME] / #46 / 게임서비스 프런트 수정
  hotfist/src/main/java/com/seok/hotfist/aggregate/MasterScore.java
  hotfist/src/main/java/com/seok/hotfist/service/GameService.java
Labels: :zap: Update

#52 [GAME] / #33, #35, #50 / 전역 변수 memNo을 GameLog에 저장
  .idea/misc.xml
  hotfist/src/main/java/com/seok/hotfist/db/gameLogDB.dat
  hotfist/src/main/java/com/seok/hotfist/repository/GameRepository.java
  hotfist/src/main/java/com/seok/hotfist/run/Application2.java
  hotfist/src/main/java/com/seok/hotfist/service/GameService.java
  hotfist/src/main/java/com/seok/hotfist/service/RankService.java
Labels: :bug: bug, :sparkles: enhancement, :zap: Update

#57 랭크 반영 버그 재수정 및 회원가입 시 아이디 중복체크 기능 구현
  hotfist/src/main/java/com/seok/hotfist/aggregate/GameLog.java
  hotfist/src/main/java/com/seok/hotfist/aggregate/MasterScore.java
  hotfist/src/main/java/com/seok/hotfist/aggregate/Member.java
  hotfist/src/main/java/com/seok/hotfist/aggregate/Status.java
  hotfist/src/main/java/com/seok/hotfist/db/gameLogDB.dat
  hotfist/src/main/java/com/seok/hotfist/db/memberDB.dat
  hotfist/src/main/java/com/seok/hotfist/db/rankDB.dat
  hotfist/src/main/java/com/seok/hotfist/repository/GameRepository.java
  hotfist/src/main/java/com/seok/hotfist/repository/MemberRepository.java
  hotfist/src/main/java/com/seok/hotfist/repository/RankRepository.java
  hotfist/src/main/java/com/seok/hotfist/run/Application3.java
  hotfist/src/main/java/com/seok/hotfist/service/GameService.java
  hotfist/src/main/java/com/seok/hotfist/service/MemberService.java
  hotfist/src/main/java/com/seok/hotfist/service/RankService.java
Labels: :bug: bug, :sparkles: enhancement
